dist: trusty
language: node_js
node_js:
  - "6.10.0"
  - "8"
python:
  - "3.6"
sudo: required

services:
  - docker

cache:
  directories:
    - ui/node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
script: 
  - ./setup.sh
  - pip install --upgrade pip
  - pip install pylint 
  - cd components
  - pylint -E core
  - cd core
  - python setup.py test
  - cd $TRAVIS_BUILD_DIR
  - cd ui && npm install && npm test
  - docker build --build-arg VCS_REF=`git rev-parse --short HEAD`   --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` -t scoreucsc/bassa  .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push scoreucsc/bassa;
    curl -X POST 'https://hooks.microbadger.com/images/scoreucsc/bassa/Wbi5zehDMooS3ri2bgC8LETGGuQ=';
    fi

