kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: bassa-monitoring
spec:
  selector:
    app: node-exporter
  ports:
  - name: node-exporter
    protocol: TCP
    port: 9100
    targetPort: 9100